version: '3.9'
services:
  jenkins:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: jenkins
    restart: always
    privileged: true
    user: root

    healthcheck:
      test: curl -s https://localhost:8080 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 1m
      timeout: 5s
      retries: 3

    ports:
      - '8080:8080'
    networks:
      - default
    volumes:
      - '$PWD/config:/var/opt/gitlab/config'
      - '$PWD/logs:/var/opt/gitlab/logs'
      - '$PWD/data:/var/opt/gitlab/data'
    environment:
      EXTERNAL_URL: 'http://gitlab.example.com'
